import type { Metadata } from "next";
import { Oranienbaum } from "next/font/google";
import "../scss/global.scss";
import AppNavigation from "@/components/app-navigation/AppNavigation";
import AppFooter from "@/components/app-footer/AppFooter";

const oranienbaum = Oranienbaum({
    variable: '--font-oranienbaum',
    subsets: ["latin"],
    style: 'normal',
    weight: ['400'],
    display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={oranienbaum.className}>
        <body>
            <header className="container">
                <AppNavigation/>
            </header>
            <main>
                {children}
            </main>
            <AppFooter/>
        </body>
    </html>
  );
}
