import type { Metadata } from "next";
import { Oranienbaum } from "next/font/google";


const oranienbaum = Oranienbaum({
    variable: '--font-oranienbaum',
    subsets: ["latin"],
    style: 'normal',
    weight: ['400'],
    display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={oranienbaum.className}>
        <body>
          
            <main>
                {children}
            </main>
     
        </body>
    </html>
  );
}
